[[lexbor]]
arch = "aarch64"
git-tree-sha1 = "00342db7c05bf19aa25b59a5a387b7dc7fad34b4"
os = "macos"

    [[lexbor.download]]
    sha256 = "1dda8df953a0229a160aa8a79458f01b057ea745da96b72a303bd579ba352a6e"
    url = "https://github.com/JuliaBinaryWrappers/lexbor_jll.jl/releases/download/lexbor-v2.4.0+0/lexbor.v2.4.0.aarch64-apple-darwin.tar.gz"
[[lexbor]]
arch = "aarch64"
git-tree-sha1 = "1e9834394b8e6aa3be724832c8f46542671deda1"
libc = "glibc"
os = "linux"

    [[lexbor.download]]
    sha256 = "d48486699dd1e054ba55a31d43f9d1d24ecb2847b0b590c6f69aacc628bca569"
    url = "https://github.com/JuliaBinaryWrappers/lexbor_jll.jl/releases/download/lexbor-v2.4.0+0/lexbor.v2.4.0.aarch64-linux-gnu.tar.gz"
[[lexbor]]
arch = "aarch64"
git-tree-sha1 = "b73ab2cebcc3e63e3c988f81b5eb661a801a231c"
libc = "musl"
os = "linux"

    [[lexbor.download]]
    sha256 = "5b62bea96cff311c470e0529ea9f96b73c0b2113145504afbf0f1b1b7f0a445e"
    url = "https://github.com/JuliaBinaryWrappers/lexbor_jll.jl/releases/download/lexbor-v2.4.0+0/lexbor.v2.4.0.aarch64-linux-musl.tar.gz"
[[lexbor]]
arch = "aarch64"
git-tree-sha1 = "2e24beddeb52b3d67ab96d7169afb2e8223c516c"
os = "freebsd"

    [[lexbor.download]]
    sha256 = "4417e1820f96213b2a7f6d6ef16194b5cf912cb6d35887d5a4b2fe9f4a37a898"
    url = "https://github.com/JuliaBinaryWrappers/lexbor_jll.jl/releases/download/lexbor-v2.4.0+0/lexbor.v2.4.0.aarch64-unknown-freebsd.tar.gz"
[[lexbor]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9503a98c4f67c3a135953db940afbfe77a6a9377"
libc = "glibc"
os = "linux"

    [[lexbor.download]]
    sha256 = "ac209b7a6e6f05e5e0bce635ee77e01d59c1a29b98e5ca61505500c1bfb6808a"
    url = "https://github.com/JuliaBinaryWrappers/lexbor_jll.jl/releases/download/lexbor-v2.4.0+0/lexbor.v2.4.0.armv6l-linux-gnueabihf.tar.gz"
[[lexbor]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "27d8c03d19c76487bb8867cfbc3e9b496941d105"
libc = "musl"
os = "linux"

    [[lexbor.download]]
    sha256 = "e30e2634611f3b556fd97d40989e6f57bf58b265e58a1a8994978a49a1c37ee3"
    url = "https://github.com/JuliaBinaryWrappers/lexbor_jll.jl/releases/download/lexbor-v2.4.0+0/lexbor.v2.4.0.armv6l-linux-musleabihf.tar.gz"
[[lexbor]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2ebd21b33b7e2a99418d47d7c9133496f63dee5a"
libc = "glibc"
os = "linux"

    [[lexbor.download]]
    sha256 = "8bfe67d3e4609cdba3590784f44765ffdda2c8ee3989168b3411c935ce975ef1"
    url = "https://github.com/JuliaBinaryWrappers/lexbor_jll.jl/releases/download/lexbor-v2.4.0+0/lexbor.v2.4.0.armv7l-linux-gnueabihf.tar.gz"
[[lexbor]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2d7eed73c4ac4911330b68d76fb5d18054e6abe3"
libc = "musl"
os = "linux"

    [[lexbor.download]]
    sha256 = "76c6907f2a55239083d30f1c2aa1abe70a663c2bd805f409953e227cb16e442b"
    url = "https://github.com/JuliaBinaryWrappers/lexbor_jll.jl/releases/download/lexbor-v2.4.0+0/lexbor.v2.4.0.armv7l-linux-musleabihf.tar.gz"
[[lexbor]]
arch = "i686"
git-tree-sha1 = "219e8cafe03643ed49cb5e05518fbcfb4efbb158"
libc = "glibc"
os = "linux"

    [[lexbor.download]]
    sha256 = "96e1474d43ef0afe3eff07bc54c11a3633d086232574ee430d69d54baaa70aad"
    url = "https://github.com/JuliaBinaryWrappers/lexbor_jll.jl/releases/download/lexbor-v2.4.0+0/lexbor.v2.4.0.i686-linux-gnu.tar.gz"
[[lexbor]]
arch = "i686"
git-tree-sha1 = "3c354329eea0e2cfcd1c94bfdbe513037168bfef"
libc = "musl"
os = "linux"

    [[lexbor.download]]
    sha256 = "0c804d9df34120029020762db0a0457a3d087c4ea12716005c28f0c6aa892a9a"
    url = "https://github.com/JuliaBinaryWrappers/lexbor_jll.jl/releases/download/lexbor-v2.4.0+0/lexbor.v2.4.0.i686-linux-musl.tar.gz"
[[lexbor]]
arch = "i686"
git-tree-sha1 = "b9b056658b9e95867bd7ea95b02ef47c14de0b87"
os = "windows"

    [[lexbor.download]]
    sha256 = "4e337ecefd277ba7023f7c598900ba86ebded36524cf29a5b07f534983bf8e2e"
    url = "https://github.com/JuliaBinaryWrappers/lexbor_jll.jl/releases/download/lexbor-v2.4.0+0/lexbor.v2.4.0.i686-w64-mingw32.tar.gz"
[[lexbor]]
arch = "powerpc64le"
git-tree-sha1 = "24c2ec018b0e824efd2d586f59695d1e6528e174"
libc = "glibc"
os = "linux"

    [[lexbor.download]]
    sha256 = "07285a6ae3a657fe55364a75bda8cd35e23b371ddc8b9201d4b1a07770584eb7"
    url = "https://github.com/JuliaBinaryWrappers/lexbor_jll.jl/releases/download/lexbor-v2.4.0+0/lexbor.v2.4.0.powerpc64le-linux-gnu.tar.gz"
[[lexbor]]
arch = "riscv64"
git-tree-sha1 = "54dd3af08db545c2837c0d883d1158d27836c18d"
libc = "glibc"
os = "linux"

    [[lexbor.download]]
    sha256 = "5a18fbc4fb9cc10c0d27108fab1c9da094415865e657d49e0d5837da59bb70bf"
    url = "https://github.com/JuliaBinaryWrappers/lexbor_jll.jl/releases/download/lexbor-v2.4.0+0/lexbor.v2.4.0.riscv64-linux-gnu.tar.gz"
[[lexbor]]
arch = "x86_64"
git-tree-sha1 = "2d373f9ab06836f481c18367b40acc67d42b461c"
os = "macos"

    [[lexbor.download]]
    sha256 = "454663bcd3fa6b5244709b41b66cc34e29d9f9b76bc86a7cae8cd2f0981ae800"
    url = "https://github.com/JuliaBinaryWrappers/lexbor_jll.jl/releases/download/lexbor-v2.4.0+0/lexbor.v2.4.0.x86_64-apple-darwin.tar.gz"
[[lexbor]]
arch = "x86_64"
git-tree-sha1 = "86e7ec66450efdf0cf4ede58c4650cb8ab6ab576"
libc = "glibc"
os = "linux"

    [[lexbor.download]]
    sha256 = "0b6c4b38d25c7f50248fe25d9dcaf1ebd8b72def6f0663dfb4cbc9bb0c5ca8b0"
    url = "https://github.com/JuliaBinaryWrappers/lexbor_jll.jl/releases/download/lexbor-v2.4.0+0/lexbor.v2.4.0.x86_64-linux-gnu.tar.gz"
[[lexbor]]
arch = "x86_64"
git-tree-sha1 = "979a00a26e1e29fa175772885e0eb4fa5e1f7d7e"
libc = "musl"
os = "linux"

    [[lexbor.download]]
    sha256 = "c20197c0a93a6a5a97f8c7d25edb7b325a894aca715f48891f901f669110a7ab"
    url = "https://github.com/JuliaBinaryWrappers/lexbor_jll.jl/releases/download/lexbor-v2.4.0+0/lexbor.v2.4.0.x86_64-linux-musl.tar.gz"
[[lexbor]]
arch = "x86_64"
git-tree-sha1 = "48752e52df91dd14043ac2a4b3edb360378f0407"
os = "freebsd"

    [[lexbor.download]]
    sha256 = "3a73bcf182f40d6748c536f829ee95843b57cb5bb9b7c1f80d7b3ec6404dcfb0"
    url = "https://github.com/JuliaBinaryWrappers/lexbor_jll.jl/releases/download/lexbor-v2.4.0+0/lexbor.v2.4.0.x86_64-unknown-freebsd.tar.gz"
[[lexbor]]
arch = "x86_64"
git-tree-sha1 = "c81d00a2560766853c28ccc2a9e6714b26b4e624"
os = "windows"

    [[lexbor.download]]
    sha256 = "27f6671c45f697d6ac7b2b4163f1b192927eaf598ef283bb7b6b0f7fcfe9baef"
    url = "https://github.com/JuliaBinaryWrappers/lexbor_jll.jl/releases/download/lexbor-v2.4.0+0/lexbor.v2.4.0.x86_64-w64-mingw32.tar.gz"
