# Autogenerated wrapper script for lexbor_jll for aarch64-apple-darwin
export liblexbor, liblexbor_core, liblexbor_css, liblexbor_dom, liblexbor_encoding, liblexbor_html, liblexbor_ns, liblexbor_punycode, liblexbor_selectors, liblexbor_tag, liblexbor_unicode, liblexbor_url, liblexbor_utils

JLLWrappers.@generate_wrapper_header("lexbor")
JLLWrappers.@declare_library_product(liblexbor, "@rpath/liblexbor.2.dylib")
JLLWrappers.@declare_library_product(liblexbor_core, "@rpath/liblexbor-core.1.dylib")
JLLWrappers.@declare_library_product(liblexbor_css, "@rpath/liblexbor-css.1.dylib")
JLLWrappers.@declare_library_product(liblexbor_dom, "@rpath/liblexbor-dom.1.dylib")
JLLWrappers.@declare_library_product(liblexbor_encoding, "@rpath/liblexbor-encoding.2.dylib")
JLLWrappers.@declare_library_product(liblexbor_html, "@rpath/liblexbor-html.2.dylib")
JLLWrappers.@declare_library_product(liblexbor_ns, "@rpath/liblexbor-ns.1.dylib")
JLLWrappers.@declare_library_product(liblexbor_punycode, "@rpath/liblexbor-punycode.1.dylib")
JLLWrappers.@declare_library_product(liblexbor_selectors, "@rpath/liblexbor-selectors.0.dylib")
JLLWrappers.@declare_library_product(liblexbor_tag, "@rpath/liblexbor-tag.1.dylib")
JLLWrappers.@declare_library_product(liblexbor_unicode, "@rpath/liblexbor-unicode.0.dylib")
JLLWrappers.@declare_library_product(liblexbor_url, "@rpath/liblexbor-url.0.dylib")
JLLWrappers.@declare_library_product(liblexbor_utils, "@rpath/liblexbor-utils.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        liblexbor,
        "lib/liblexbor.2.3.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_core,
        "lib/liblexbor-core.1.7.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_css,
        "lib/liblexbor-css.1.1.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_dom,
        "lib/liblexbor-dom.1.6.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_encoding,
        "lib/liblexbor-encoding.2.0.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_html,
        "lib/liblexbor-html.2.3.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_ns,
        "lib/liblexbor-ns.1.2.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_punycode,
        "lib/liblexbor-punycode.1.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_selectors,
        "lib/liblexbor-selectors.0.2.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_tag,
        "lib/liblexbor-tag.1.2.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_unicode,
        "lib/liblexbor-unicode.0.1.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_url,
        "lib/liblexbor-url.0.1.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_utils,
        "lib/liblexbor-utils.0.3.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
