# Autogenerated wrapper script for lexbor_jll for x86_64-w64-mingw32
export liblexbor, liblexbor_core, liblexbor_css, liblexbor_dom, liblexbor_encoding, liblexbor_html, liblexbor_ns, liblexbor_punycode, liblexbor_selectors, liblexbor_tag, liblexbor_unicode, liblexbor_url, liblexbor_utils

JLLWrappers.@generate_wrapper_header("lexbor")
JLLWrappers.@declare_library_product(liblexbor, "liblexbor.dll")
JLLWrappers.@declare_library_product(liblexbor_core, "liblexbor-core.dll")
JLLWrappers.@declare_library_product(liblexbor_css, "liblexbor-css.dll")
JLLWrappers.@declare_library_product(liblexbor_dom, "liblexbor-dom.dll")
JLLWrappers.@declare_library_product(liblexbor_encoding, "liblexbor-encoding.dll")
JLLWrappers.@declare_library_product(liblexbor_html, "liblexbor-html.dll")
JLLWrappers.@declare_library_product(liblexbor_ns, "liblexbor-ns.dll")
JLLWrappers.@declare_library_product(liblexbor_punycode, "liblexbor-punycode.dll")
JLLWrappers.@declare_library_product(liblexbor_selectors, "liblexbor-selectors.dll")
JLLWrappers.@declare_library_product(liblexbor_tag, "liblexbor-tag.dll")
JLLWrappers.@declare_library_product(liblexbor_unicode, "liblexbor-unicode.dll")
JLLWrappers.@declare_library_product(liblexbor_url, "liblexbor-url.dll")
JLLWrappers.@declare_library_product(liblexbor_utils, "liblexbor-utils.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        liblexbor,
        "bin\\liblexbor.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_core,
        "bin\\liblexbor-core.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_css,
        "bin\\liblexbor-css.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_dom,
        "bin\\liblexbor-dom.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_encoding,
        "bin\\liblexbor-encoding.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_html,
        "bin\\liblexbor-html.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_ns,
        "bin\\liblexbor-ns.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_punycode,
        "bin\\liblexbor-punycode.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_selectors,
        "bin\\liblexbor-selectors.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_tag,
        "bin\\liblexbor-tag.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_unicode,
        "bin\\liblexbor-unicode.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_url,
        "bin\\liblexbor-url.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_utils,
        "bin\\liblexbor-utils.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
