# Autogenerated wrapper script for lexbor_jll for x86_64-linux-musl
export liblexbor, liblexbor_core, liblexbor_css, liblexbor_dom, liblexbor_encoding, liblexbor_html, liblexbor_ns, liblexbor_punycode, liblexbor_selectors, liblexbor_tag, liblexbor_unicode, liblexbor_url, liblexbor_utils

JLLWrappers.@generate_wrapper_header("lexbor")
JLLWrappers.@declare_library_product(liblexbor, "liblexbor.so.2")
JLLWrappers.@declare_library_product(liblexbor_core, "liblexbor-core.so.1")
JLLWrappers.@declare_library_product(liblexbor_css, "liblexbor-css.so.1")
JLLWrappers.@declare_library_product(liblexbor_dom, "liblexbor-dom.so.1")
JLLWrappers.@declare_library_product(liblexbor_encoding, "liblexbor-encoding.so.2")
JLLWrappers.@declare_library_product(liblexbor_html, "liblexbor-html.so.2")
JLLWrappers.@declare_library_product(liblexbor_ns, "liblexbor-ns.so.1")
JLLWrappers.@declare_library_product(liblexbor_punycode, "liblexbor-punycode.so.1")
JLLWrappers.@declare_library_product(liblexbor_selectors, "liblexbor-selectors.so.0")
JLLWrappers.@declare_library_product(liblexbor_tag, "liblexbor-tag.so.1")
JLLWrappers.@declare_library_product(liblexbor_unicode, "liblexbor-unicode.so.0")
JLLWrappers.@declare_library_product(liblexbor_url, "liblexbor-url.so.0")
JLLWrappers.@declare_library_product(liblexbor_utils, "liblexbor-utils.so.0")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        liblexbor,
        "lib/liblexbor.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_core,
        "lib/liblexbor-core.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_css,
        "lib/liblexbor-css.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_dom,
        "lib/liblexbor-dom.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_encoding,
        "lib/liblexbor-encoding.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_html,
        "lib/liblexbor-html.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_ns,
        "lib/liblexbor-ns.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_punycode,
        "lib/liblexbor-punycode.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_selectors,
        "lib/liblexbor-selectors.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_tag,
        "lib/liblexbor-tag.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_unicode,
        "lib/liblexbor-unicode.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_url,
        "lib/liblexbor-url.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        liblexbor_utils,
        "lib/liblexbor-utils.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
